language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run prettier -- --list-different &&
    npm run build-css &&
    npm run build &&
    npm test -- --coverage
after_success:
  - cat ./coverage/lcov.info | coveralls
